export const FETCH_DATA_REQ="FETCH_DATA_REQ";
export const FETCH_DATA_SUC="FETCH_DATA_SUC";
export const FETCH_DATA_FAIL="FETCH_DATA_FAIL";

export const AUTHORS_FETCH_DATA_REQ="AUTHORS_FETCH_DATA_REQ";
export const AUTHORS_FETCH_DATA_SUC="AUTHORS_FETCH_DATA_SUC";
export const AUTHORS_FETCH_DATA_FAIL="AUTHORS_FETCH_DATA_FAIL";


export const TAGS_FETCH_DATA_REQ="TAGS_FETCH_DATA_REQ";
export const TAGS_FETCH_DATA_SUC="TAGS_FETCH_DATA_SUC";
export const TAGS_FETCH_DATA_FAIL="TAGS_FETCH_DATA_FAIL";
